version: "3.8"
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    image: e2j:dev
    container_name: e2j-dev

    stdin_open: true
    tty: true

    ports:
      - "1234:80"
      
    volumes:
      - ./app:/code/app


      
