version: "3.8"
services:
  buildcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    image: e2j
    container_name: e2j-build

    stdin_open: true
    tty: true
      
    volumes:
      - ..:/code

  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    image: e2j
    container_name: e2j-dev

    stdin_open: true
    tty: true

    ports:
      - "1234:80"
      
    volumes:
      - ../excel2json:/code/app

  testcontainer:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: e2j-test
    container_name: e2j-test

    stdin_open: true
    tty: true

    environment:
      - PYTHONPATH=/code/app

    volumes:
      - ../excel2json:/code/app
      - ../tests:/code/tests

    command: "/bin/bash"
  

